name: 'AdoreMe Tech PHP Checkstyle Composite Action'
description: 'Run PHP checkstyle with custom PHP image'
inputs:
  php-image:
    description: 'The PHP image to use'
    required: true
  report-path:
    description: 'PHP checkstyle report path'
    required: true
    default: './build/reports/php-checkstyle.xml'
runs:
  using: "composite"
  steps:
    - name: 'Run Checkstyle'
      run: $GITHUB_ACTION_PATH/check.sh
      shell: bash
      env:
        INPUT_PHP_IMAGE: ${{ inputs.php-image }}
        INPUT_PHPCS_REPORT_PATH: ${{ inputs.report-path }}
    - name: 'Run Checkstyle Report'
      uses: jwgmeligmeyling/checkstyle-github-action@master
      with:
        name: 'PHP Checkstyle'
        title: 'Checkstyle report'
        path: ${{ inputs.report-path }}
    - name: 'TODO: Notify in PR'
      run: |
        echo 'PHP Checkstyle Complete'
      shell: bash
