name: 'AdoreMe Tech PHP Checkstyle Composite GH Action'
description: 'Run PHP checkstyle with custom PHP image'
inputs:
  php-image:
    description: 'The PHP image to use'
    required: true
  report-dir:
    description: 'PHP checkstyle report directory'
    required: true
    default: 'build/reports'
  report-file-name:
    description: 'PHP checkstyle report file name'
    required: true
    default: 'php-checkstyle.xml'
  phpcs-standard:
    description: 'PHP checkstyle standard to use'
    required: false
    default: 'PSR2'
runs:
  using: "composite"
  steps:
    - name: 'Run Checkstyle'
      run: $GITHUB_ACTION_PATH/check.sh
      shell: bash
      env:
        INPUT_PHP_IMAGE: ${{ inputs.php-image }}
        INPUT_PHPCS_REPORT_PATH: '${{ inputs.report-dir }}/${{ inputs.report-file-name }}'
        INPUT_PHPCS_STANDARD: ${{ inputs.phpcs-standard }}
    - name: 'Run Checkstyle Report'
      uses: adore-me/checkstyle-github-action@v1.0.0
      with:
        name: 'PHP Checkstyle'
        title: 'Checkstyle report'
        path: '${{ inputs.report-dir }}/${{ inputs.report-file-name }}'
